# Generated by Django 5.0.6 on 2024-07-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnwithusai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userchatwithai',
            options={'verbose_name_plural': 'AI Chats'},
        ),
    ]
