# Generated by Django 5.0.4 on 2024-06-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0002_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='verifiedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('isVerified', models.BooleanField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name_plural': 'OTP'},
        ),
        migrations.AlterModelOptions(
            name='techblogs',
            options={'verbose_name_plural': 'All Blogs'},
        ),
    ]
