# Generated by Django 5.0.6 on 2024-06-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0005_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='hackathonRegModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=150)),
                ('college', models.CharField(max_length=150)),
                ('lead', models.CharField(max_length=150)),
                ('leadmobile', models.IntegerField()),
                ('leadmail', models.CharField(max_length=150)),
                ('mem2', models.CharField(max_length=150)),
                ('m2mobile', models.IntegerField()),
                ('mem3', models.CharField(max_length=150)),
                ('m3mobile', models.IntegerField()),
                ('year', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Hackathon Registration',
            },
        ),
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name_plural': 'Queries'},
        ),
        migrations.AlterModelOptions(
            name='verifiedemail',
            options={'verbose_name_plural': 'Manual Email Verifications'},
        ),
    ]
