# Generated by Django 5.0.6 on 2024-06-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0006_hackathonregmodel_alter_contactmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('desc', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Internship Data',
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'Registered Users'},
        ),
        migrations.AlterModelOptions(
            name='hackathonregmodel',
            options={'verbose_name_plural': 'Hackathon Registrations'},
        ),
    ]
