# Generated by Django 5.0.6 on 2024-06-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0007_internshipmodel_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='opportunities/internships/'),
        ),
    ]
