# Generated by Django 5.0.6 on 2024-06-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0008_alter_internshipmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipmodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='opportunities/'),
        ),
    ]
