# Generated by Django 5.0.6 on 2024-06-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0009_alter_internshipmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetetionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='opportunities/competetion')),
                ('desc', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Hackathon and Competetion Data',
            },
        ),
        migrations.AlterField(
            model_name='internshipmodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='opportunities/internships'),
        ),
    ]
