# Generated by Django 5.0.6 on 2024-06-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0011_alter_competetionmodel_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='scholarshipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='opportunities/scholarships')),
                ('desc', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Scholarship Data',
            },
        ),
    ]
