# Generated by Django 5.0.6 on 2024-06-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0012_scholarshipmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='opportunities/jobs')),
                ('desc', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Opp-Job Data',
            },
        ),
        migrations.AlterModelOptions(
            name='competetionmodel',
            options={'verbose_name_plural': 'Opp-Hackathon and Competetion Data'},
        ),
        migrations.AlterModelOptions(
            name='internshipmodel',
            options={'verbose_name_plural': 'Opp-Internship Data'},
        ),
        migrations.AlterModelOptions(
            name='scholarshipmodel',
            options={'verbose_name_plural': 'Opp-Scholarship Data'},
        ),
    ]
