# Generated by Django 5.0.6 on 2024-07-19 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0015_userchatwithai'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userChatWithAI',
        ),
    ]
