# Generated by Django 5.0.6 on 2024-07-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0016_delete_userchatwithai'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompetetionModel',
        ),
        migrations.DeleteModel(
            name='InternshipModel',
        ),
        migrations.DeleteModel(
            name='jobModel',
        ),
        migrations.DeleteModel(
            name='scholarshipModel',
        ),
    ]
