# Generated by Django 5.0.6 on 2024-07-22 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0017_delete_competetionmodel_delete_internshipmodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactModel',
        ),
    ]
