# Generated by Django 5.0.6 on 2024-08-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0018_delete_contactmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='useremail',
            field=models.CharField(max_length=150),
        ),
    ]
