# Generated by Django 5.0.6 on 2024-08-06 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testCaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testID', models.IntegerField()),
                ('testcases', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='programminQuestionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionID', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('testcases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_programmingHub.testcasemodel')),
            ],
        ),
    ]
