# Generated by Django 5.0.6 on 2024-08-06 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_programmingHub', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='programminQuestionsModel',
            new_name='programmingQuestionsModel',
        ),
    ]
