# Generated by Django 5.0.6 on 2024-08-06 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_programmingHub', '0002_rename_programminquestionsmodel_programmingquestionsmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmingquestionsmodel',
            name='testcases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='app_programmingHub.testcasemodel'),
        ),
        migrations.CreateModel(
            name='submissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submissionID', models.IntegerField()),
                ('submissionDetail', models.CharField(max_length=250)),
                ('submittedAt', models.DateTimeField(auto_now_add=True)),
                ('submittedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
