# Generated by Django 5.0.6 on 2024-08-07 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_programmingHub', '0003_alter_programmingquestionsmodel_testcases_and_more'),
    ]

    operations = [
    ]
