# Generated by Django 5.0.6 on 2024-08-07 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_programmingHub', '0005_programmingquestionsmodel_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionmodel',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='app_programmingHub.programmingquestionsmodel'),
        ),
    ]
