# Generated by Django 5.0.6 on 2024-07-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('college', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=150)),
                ('question', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Queries',
            },
        ),
    ]
