# Generated by Django 5.0.6 on 2024-07-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetetionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='opportunities/competetion')),
                ('desc', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Opp-Hackathon and Competetion Data',
            },
        ),
        migrations.CreateModel(
            name='InternshipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='opportunities/internships')),
                ('desc', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Opp-Internship Data',
            },
        ),
        migrations.CreateModel(
            name='jobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='opportunities/jobs')),
                ('desc', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Opp-Job Data',
            },
        ),
        migrations.CreateModel(
            name='scholarshipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='opportunities/scholarships')),
                ('desc', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Opp-Scholarship Data',
            },
        ),
    ]
