# Generated by Django 5.0.6 on 2024-08-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_courses', '0006_linuxmcqmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cssmcqmodel',
            options={'verbose_name_plural': 'CSS MCQs'},
        ),
        migrations.AlterModelOptions(
            name='linuxmcqmodel',
            options={'verbose_name_plural': 'Linux MCQs'},
        ),
        migrations.AlterModelOptions(
            name='matplotlibmcqmodel',
            options={'verbose_name_plural': 'MatplotLib MCQs'},
        ),
        migrations.AlterModelOptions(
            name='numpymcqmodel',
            options={'verbose_name_plural': 'Numpy MCQs'},
        ),
        migrations.AlterModelOptions(
            name='pandasmcqmodel',
            options={'verbose_name_plural': 'Pandas MCQs'},
        ),
        migrations.AlterModelOptions(
            name='pythonmcqmodel',
            options={'verbose_name_plural': 'Python MCQs'},
        ),
        migrations.AddField(
            model_name='cssmcqmodel',
            name='topictag',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='linuxmcqmodel',
            name='topictag',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='matplotlibmcqmodel',
            name='topictag',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='numpymcqmodel',
            name='topictag',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='pandasmcqmodel',
            name='topictag',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='pythonmcqmodel',
            name='topictag',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
